#!/usr/bin/env python3
"""Generates SwiftTerm configuration code for common terminal setups."""

import sys
import json
import argparse


PRESETS = {
    "ssh": {
        "description": "SSH remote session via SwiftNIO or NMSSH",
        "font": "Menlo",
        "size": 14,
        "scrollback": 5000,
        "theme": "dracula",
        "accessibility": True,
    },
    "local": {
        "description": "Local shell process (LocalProcessTerminalView)",
        "font": "SF Mono",
        "size": 13,
        "scrollback": 3000,
        "theme": "system",
        "accessibility": True,
    },
    "iterm2-compat": {
        "description": "iTerm2-compatible with inline image protocol support",
        "font": "JetBrains Mono",
        "size": 14,
        "scrollback": 10000,
        "theme": "one-dark",
        "accessibility": False,
    },
}

THEMES = {
    "dracula": {
        "foreground": "(0.933, 0.910, 0.835)",
        "background": "(0.157, 0.173, 0.212)",
        "cursor":     "(0.973, 0.973, 0.949)",
        "selection":  "(0.271, 0.302, 0.392)",
        "black":      "(0.298, 0.337, 0.416)",
        "red":        "(0.753, 0.286, 0.318)",
        "green":      "(0.639, 0.745, 0.549)",
        "yellow":     "(0.933, 0.749, 0.408)",
        "blue":       "(0.506, 0.631, 0.757)",
        "magenta":    "(0.694, 0.557, 0.820)",
        "cyan":       "(0.533, 0.753, 0.816)",
        "white":      "(0.847, 0.871, 0.914)",
    },
    "one-dark": {
        "foreground": "(0.788, 0.808, 0.855)",
        "background": "(0.153, 0.169, 0.212)",
        "cursor":     "(0.529, 0.596, 0.702)",
        "selection":  "(0.200, 0.227, 0.286)",
        "black":      "(0.231, 0.247, 0.298)",
        "red":        "(0.902, 0.329, 0.376)",
        "green":      "(0.573, 0.796, 0.427)",
        "yellow":     "(0.898, 0.718, 0.357)",
        "blue":       "(0.396, 0.647, 0.929)",
        "magenta":    "(0.753, 0.463, 0.847)",
        "cyan":       "(0.341, 0.769, 0.820)",
        "white":      "(0.788, 0.808, 0.855)",
    },
    "system": {
        "foreground": "(0.800, 0.800, 0.800)",
        "background": "(0.067, 0.067, 0.067)",
        "cursor":     "(0.900, 0.900, 0.900)",
        "selection":  "(0.200, 0.400, 0.700)",
        "black":      "(0.0, 0.0, 0.0)",
        "red":        "(0.800, 0.200, 0.200)",
        "green":      "(0.200, 0.700, 0.200)",
        "yellow":     "(0.700, 0.700, 0.200)",
        "blue":       "(0.200, 0.400, 0.800)",
        "magenta":    "(0.600, 0.200, 0.600)",
        "cyan":       "(0.200, 0.600, 0.700)",
        "white":      "(0.800, 0.800, 0.800)",
    },
}


def memory_tier_scrollback():
    """Return scrollback line counts per memory tier."""
    return {
        "≥8 GB (high-end device)": 10000,
        "4-8 GB (mid-range)": 5000,
        "<4 GB (constrained)": 1000,
    }


def generate_swift_config(font: str, size: int, scrollback: int, theme_name: str,
                           preset: str, accessibility: bool) -> str:
    colors = THEMES.get(theme_name, THEMES["dracula"])
    lines = []

    lines.append("// MARK: - SwiftTerm Configuration")
    lines.append("// Generated by terminal_config_generator.py")
    lines.append(f"// Preset: {preset}")
    lines.append("")
    lines.append("import SwiftTerm")
    lines.append("import UIKit")
    lines.append("")

    # Theme struct
    lines.append("struct AppTerminalTheme: ColorSource {")
    for color_name, rgb in colors.items():
        r, g, b = rgb.strip("()").split(", ")
        lines.append(f"    var {color_name}: Color {{")
        lines.append(f"        Color(red: {r}, green: {g}, blue: {b}, alpha: 1)")
        lines.append("    }")
    lines.append("}")
    lines.append("")

    # Setup function
    lines.append("func configureTerminal(_ terminal: LocalProcessTerminalView, session: Any? = nil) {")
    lines.append(f"    // Font: {font} {size}pt")
    lines.append(f"    terminal.font = UIFont(name: \"{font}\", size: {size})")
    lines.append(f"        ?? UIFont.monospacedSystemFont(ofSize: {size}, weight: .regular)")
    lines.append("")
    lines.append(f"    // Theme: {theme_name}")
    lines.append("    terminal.installColors(AppTerminalTheme())")
    lines.append("")
    lines.append(f"    // Scrollback: {scrollback} lines")
    lines.append(f"    terminal.terminal.options.scrollback = {scrollback}")
    lines.append("")

    # Memory-adaptive scrollback
    lines.append("    // Adaptive scrollback based on device memory")
    tiers = memory_tier_scrollback()
    lines.append("    let memory = ProcessInfo.processInfo.physicalMemory")
    lines.append("    if memory < 4_000_000_000 {")
    lines.append(f"        terminal.terminal.options.scrollback = {tiers['<4 GB (constrained)']}")
    lines.append("    } else if memory < 8_000_000_000 {")
    lines.append(f"        terminal.terminal.options.scrollback = {tiers['4-8 GB (mid-range)']}")
    lines.append("    }")
    lines.append("")

    if accessibility:
        lines.append("    // Accessibility")
        lines.append("    terminal.isAccessibilityElement = true")
        lines.append("    terminal.accessibilityLabel = \"Terminal\"")
        lines.append("    terminal.accessibilityTraits = [.updatesFrequently]")
        lines.append("")

    lines.append("}")

    return "\n".join(lines)


def generate_json_config(font: str, size: int, scrollback: int, theme_name: str,
                          preset: str, accessibility: bool) -> str:
    config = {
        "preset": preset,
        "font": {"name": font, "size": size},
        "theme": theme_name,
        "colors": THEMES.get(theme_name, THEMES["dracula"]),
        "scrollback": {
            "default": scrollback,
            "tiers": memory_tier_scrollback(),
        },
        "accessibility": accessibility,
        "accessibility_checklist": [
            "isAccessibilityElement = true",
            "accessibilityLabel includes hostname",
            "accessibilityTraits includes updatesFrequently",
            "Dynamic Type scaling applied to font size",
        ] if accessibility else [],
    }
    return json.dumps(config, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description="Generate SwiftTerm configuration code",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Usage:\n"
            "  python terminal_config_generator.py --preset ssh\n"
            "  python terminal_config_generator.py --theme dracula --font Menlo --size 14\n"
            "  python terminal_config_generator.py --preset local --format json"
        )
    )
    parser.add_argument("--preset", choices=list(PRESETS.keys()),
                        help="Predefined configuration preset")
    parser.add_argument("--theme", choices=list(THEMES.keys()), default="dracula")
    parser.add_argument("--font", default="Menlo")
    parser.add_argument("--size", type=int, default=14)
    parser.add_argument("--scrollback", type=int, default=5000)
    parser.add_argument("--no-accessibility", action="store_true")
    parser.add_argument("--format", choices=["swift", "json"], default="swift")
    args = parser.parse_args()

    # Apply preset defaults
    preset_name = args.preset or "custom"
    if args.preset and args.preset in PRESETS:
        p = PRESETS[args.preset]
        font = args.font if args.font != "Menlo" else p["font"]
        size = args.size if args.size != 14 else p["size"]
        scrollback = args.scrollback if args.scrollback != 5000 else p["scrollback"]
        theme = args.theme if args.theme != "dracula" else p["theme"]
        accessibility = p["accessibility"] and not args.no_accessibility
    else:
        font = args.font
        size = args.size
        scrollback = args.scrollback
        theme = args.theme
        accessibility = not args.no_accessibility

    if theme not in THEMES:
        theme = "dracula"

    if args.format == "json":
        print(generate_json_config(font, size, scrollback, theme, preset_name, accessibility))
    else:
        print(generate_swift_config(font, size, scrollback, theme, preset_name, accessibility))


if __name__ == "__main__":
    main()
