#!/usr/bin/env python3
"""Generates visionOS WindowGroup scene configurations for spatial applications."""

import sys
import json
import argparse


PRESETS = {
    "dashboard": {
        "windows": [
            {"id": "main", "style": "plain", "width": 900, "height": 600, "label": "Main Dashboard"},
            {"id": "detail", "style": "plain", "width": 600, "height": 800, "label": "Detail Panel"},
            {"id": "settings", "style": "plain", "width": 500, "height": 600, "label": "Settings"},
        ],
        "immersive": None,
        "shared_state": True,
    },
    "spatial": {
        "windows": [
            {"id": "main", "style": "plain", "width": 800, "height": 500, "label": "Control Panel"},
            {"id": "model-view", "style": "volumetric",
             "width_m": 0.8, "height_m": 0.8, "depth_m": 0.8, "label": "3D Model"},
        ],
        "immersive": {"id": "spatial-env", "style": "mixed"},
        "shared_state": True,
    },
    "immersive-first": {
        "windows": [
            {"id": "launcher", "style": "plain", "width": 600, "height": 400, "label": "Launcher"},
        ],
        "immersive": {"id": "main-space", "style": "full"},
        "shared_state": False,
    },
}


def generate_window_group(w: dict) -> list[str]:
    lines = []
    label = w.get("label", w["id"])

    if w["style"] == "volumetric":
        wm = w.get("width_m", 0.6)
        hm = w.get("height_m", 0.6)
        dm = w.get("depth_m", 0.6)
        lines += [
            f'        // {label}',
            f'        WindowGroup(id: "{w["id"]}") {{',
            f'            {w["id"].replace("-", "_").title().replace("_", "")}View()',
            '        }',
            '        .windowStyle(.volumetric)',
            f'        .defaultSize(width: {wm}, height: {hm}, depth: {dm}, in: .meters)',
        ]
    else:
        width = w.get("width", 800)
        height = w.get("height", 600)
        lines += [
            f'        // {label}',
            f'        WindowGroup(id: "{w["id"]}") {{',
            f'            {w["id"].replace("-", "_").title().replace("_", "")}View()',
            '        }',
            '        .windowStyle(.plain)',
            f'        .defaultSize(width: {width}, height: {height})',
        ]
    return lines


def generate_immersive_space(imm: dict) -> list[str]:
    style_map = {
        "mixed": ".mixed",
        "full": ".full",
        "progressive": ".progressive",
    }
    style = style_map.get(imm["style"], ".mixed")
    return [
        f'        // Immersive Space: {imm["id"]}',
        f'        ImmersiveSpace(id: "{imm["id"]}") {{',
        '            ImmersiveView()',
        '        }',
        f'        .immersionStyle(selection: .constant({style}), in: {style})',
    ]


def generate_state_class(windows: list[dict], has_immersive: bool) -> list[str]:
    lines = [
        "",
        "@Observable",
        "class AppState {",
        "    var openWindows: Set<String> = [\"main\"]",
    ]
    if has_immersive:
        lines.append("    var immersiveSpaceOpen = false")
    lines += [
        "    var selectedItem: AnyHashable?",
        "",
        "    func open(_ windowId: String) { openWindows.insert(windowId) }",
        "    func close(_ windowId: String) { openWindows.remove(windowId) }",
        "}",
    ]
    return lines


def generate_swift(preset_config: dict, preset_name: str) -> str:
    windows = preset_config["windows"]
    immersive = preset_config.get("immersive")
    shared_state = preset_config.get("shared_state", True)

    lines = [
        "// visionOS Window Layout",
        f"// Preset: {preset_name}",
        "// Generated by visionos_window_layout_generator.py",
        "",
        "import SwiftUI",
        "import RealityKit",
        "",
        "@main",
        "struct SpatialApp: App {",
    ]

    if shared_state:
        lines.append("    @State private var appState = AppState()")
        lines.append("")

    lines.append("    var body: some Scene {")

    all_window_lines = []
    for i, w in enumerate(windows):
        wlines = generate_window_group(w)
        if i > 0:
            all_window_lines.append("")
        all_window_lines.extend(wlines)
        if shared_state:
            all_window_lines.append("        .environment(appState)")

    lines.extend(all_window_lines)

    if immersive:
        lines.append("")
        lines.extend(generate_immersive_space(immersive))

    lines += [
        "    }",
        "}",
    ]

    if shared_state:
        lines.extend(generate_state_class(windows, bool(immersive)))

    return "\n".join(lines)


def generate_json_output(preset_config: dict, preset_name: str) -> str:
    config = {
        "preset": preset_name,
        "windows": preset_config["windows"],
        "immersive_space": preset_config.get("immersive"),
        "shared_state": preset_config.get("shared_state", True),
        "recommendations": [
            "Use .windowStyle(.plain) for 2D panels",
            "Use .windowStyle(.volumetric) for 3D content containers",
            "Share AppState via @Environment across all windows",
            "Persist window placement with @SceneStorage",
            "Test window layering with multiple windows open simultaneously",
        ],
    }
    return json.dumps(config, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description="Generate visionOS WindowGroup scene configurations",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Usage:\n"
            "  python visionos_window_layout_generator.py --preset dashboard\n"
            "  python visionos_window_layout_generator.py --preset spatial --format json\n"
            "  python visionos_window_layout_generator.py --windows 3 --style plain"
        )
    )
    parser.add_argument("--preset", choices=list(PRESETS.keys()),
                        help="Predefined layout preset")
    parser.add_argument("--windows", type=int, default=2,
                        help="Number of windows (used if no preset)")
    parser.add_argument("--style", choices=["plain", "volumetric", "immersive"],
                        default="plain", help="Window style (used if no preset)")
    parser.add_argument("--format", choices=["swift", "json"], default="swift")
    args = parser.parse_args()

    if args.preset:
        config = PRESETS[args.preset]
        preset_name = args.preset
    else:
        config = {
            "windows": [
                {"id": f"window-{i+1}", "style": args.style,
                 "width": 800, "height": 600, "label": f"Window {i+1}"}
                for i in range(args.windows)
            ],
            "immersive": None,
            "shared_state": True,
        }
        preset_name = "custom"

    if args.format == "json":
        print(generate_json_output(config, preset_name))
    else:
        print(generate_swift(config, preset_name))


if __name__ == "__main__":
    main()
